version: '3.9'

services:
  # nginx
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx_server_ente
    ports:
      - 80:80
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./api:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  # API
  api: &api
    container_name: api_ente
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./api:/var/www/html
    environment:
      TZ: Asia/Tokyo
    expose:
      - 9000
    tty: true
    depends_on:
      - database
      - redis

  # database
  database:
    container_name: database_ente
    platform: 'linux/amd64'
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ente_db
      TZ: Asia/Tokyo
    volumes:
      - docker-db-mysql:/var/lib/mysql
      - ./docker/db/sql:/docker-entrypoint-initdb.d

  # redis
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "docker-redis:/data"
      # - "docker/redis/redis.conf:/etc/redis.conf"

  # 開発用DBエディタ
  phpmyadmin:
    container_name: phpmyadmin_ente
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOSTS=database
      - PMA_USER=root
      - PMA_PASSWORD=root

  phpredisadmin:
    container_name: phpredisadmin_ente
    image: erikdubbelboer/phpredisadmin:latest
    ports:
      - "8980:80"
    environment:
      REDIS_1_HOST: redis

volumes:
  docker-db-mysql:
  docker-redis:
